server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:aitool
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
logging.level.org.springframework: INFO
